#!/usr/bin/env python2.7

import argparse
import os
import re

from extract import extract_stat
from paths import st_stat_dir

parser = argparse.ArgumentParser(description='check sum of slots',
                                prefix_chars='-')

parser.add_argument('-s', '--stats',
                    default='./stats.txt',
                    help='stats.txt to be converted')

parser.add_argument('-t', '--tail', action='store_true',
                    help='use statistics in tail of stats.txt')

args = parser.parse_args()

def speculate_name():
    d = {
        'perl': 'perlbench',
        'libq': 'libquantum',
    }

    cwd = os.getcwd()
    m = re.match('.*/(\w+)_\w+$', cwd, re.M)
    if not m is None:
        short_name = m.group(1)
        if d.has_key(short_name):
            return d[short_name]
        else:
            return short_name
    else:
        return re.match('.*/(\w+)$', cwd, re.M).group(1)


print extract_stat(args.stats, args.tail,
                   st_stat_dir() + speculate_name() + '/stats.txt')
